import { Injectable } from '@nestjs/common';

const getUrlToPhoto = async (word: string) => {
  const API_KEY = 'YOUR_KEY';
  const URL = 'https://pixabay.com/api/?key=' + API_KEY + '&q=' + encodeURIComponent(word) + '&orientation=vertical';

  const results = await fetch(URL);
  if (results.ok) {
    const resultsJson = await results.json();
    if (resultsJson.hits.length > 0) {
      return resultsJson.hits.at(0).webformatURL as string;
    }

    return '';
  }

  return '';
};

@Injectable()
export class AppService {
  async getRandomWord() {
    const randomEnglishWords = [
      'Aardvark',
      'Albatross',
      'Alligator',
      'Alpaca',
      'Ant',
      'Anteater',
      'Antelope',
      'Ape',
      'Armadillo',
      'Donkey',
      'Baboon',
      'Badger',
      'Barracuda',
      'Bat',
      'Bear',
      'Beaver',
      'Bee',
      'Bison',
      'Boar',
      'Buffalo',
      'Butterfly',
      'Camel',
      'Capybara',
      'Caribou',
      'Cassowary',
      'Cat',
      'Caterpillar',
      'Cattle',
      'Chamois',
      'Cheetah',
      'Chicken',
      'Chimpanzee',
      'Chinchilla',
      'Chough',
      'Clam',
      'Cobra',
      'Cockroach',
      'Cod',
      'Cormorant',
      'Coyote',
      'Crab',
      'Crane',
      'Crocodile',
      'Crow',
      'Curlew',
      'Deer',
      'Dinosaur',
      'Dog',
      'Dogfish',
      'Dolphin',
      'Dotterel',
      'Dove',
      'Dragonfly',
      'Duck',
      'Dugong',
      'Dunlin',
      'Eagle',
      'Echidna',
      'Eel',
      'Eland',
      'Elephant',
      'Elk',
      'Emu',
      'Falcon',
      'Ferret',
      'Finch',
      'Fish',
      'Flamingo',
      'Fly',
      'Fox',
      'Frog',
      'Gaur',
      'Gazelle',
      'Gerbil',
      'Giraffe',
      'Gnat',
      'Gnu',
      'Goat',
      'Goldfinch',
      'Goldfish',
      'Goose',
      'Gorilla',
      'Goshawk',
      'Grasshopper',
      'Grouse',
      'Guanaco',
      'Gull',
      'Hamster',
      'Hare',
      'Hawk',
      'Hedgehog',
      'Heron',
      'Herring',
      'Hippopotamus',
      'Hornet',
      'Horse',
      'Human',
      'Hummingbird',
      'Hyena',
      'Ibex',
      'Ibis',
      'Jackal',
      'Jaguar',
      'Jay',
      'Jellyfish',
      'Kangaroo',
      'Kingfisher',
      'Koala',
      'Kookabura',
      'Kouprey',
      'Kudu',
      'Lapwing',
      'Lark',
      'Lemur',
      'Leopard',
      'Lion',
      'Llama',
      'Lobster',
      'Locust',
      'Loris',
      'Louse',
      'Lyrebird',
      'Magpie',
      'Mallard',
      'Manatee',
      'Mandrill',
      'Mantis',
      'Marten',
      'Meerkat',
      'Mink',
      'Mole',
      'Mongoose',
      'Monkey',
      'Moose',
      'Mosquito',
      'Mouse',
      'Mule',
      'Narwhal',
      'Newt',
      'Nightingale',
      'Octopus',
      'Okapi',
      'Opossum',
      'Oryx',
      'Ostrich',
      'Otter',
      'Owl',
      'Oyster',
      'Panther',
      'Parrot',
      'Partridge',
      'Peafowl',
      'Pelican',
      'Penguin',
      'Pheasant',
      'Pig',
      'Pigeon',
      'Pony',
      'Porcupine',
      'Porpoise',
      'Quail',
      'Quelea',
      'Quetzal',
      'Rabbit',
      'Raccoon',
      'Rail',
      'Ram',
      'Rat',
      'Raven',
      'Red deer',
      'Red panda',
      'Reindeer',
      'Rhinoceros',
      'Rook',
      'Salamander',
      'Salmon',
      'Sand Dollar',
      'Sandpiper',
      'Sardine',
      'Scorpion',
      'Seahorse',
      'Seal',
      'Shark',
      'Sheep',
      'Shrew',
      'Skunk',
      'Snail',
      'Snake',
      'Sparrow',
      'Spider',
      'Spoonbill',
      'Squid',
      'Squirrel',
      'Starling',
      'Stingray',
      'Stinkbug',
      'Stork',
      'Swallow',
      'Swan',
      'Tapir',
      'Tarsier',
      'Termite',
      'Tiger',
      'Toad',
      'Trout',
      'Turkey',
      'Turtle',
      'Viper',
      'Vulture',
      'Wallaby',
      'Walrus',
      'Wasp',
      'Weasel',
      'Whale',
      'Wildcat',
      'Wolf',
      'Wombat',
      'Woodcock',
      'Woodpecker',
      'Worm',
      'Wren',
      'Yak',
      'Zebra',
    ];
    const chosenRandomWord = randomEnglishWords[Math.floor(Math.random() * randomEnglishWords.length)];
    const url = await getUrlToPhoto(chosenRandomWord);
    const notChosenWords = randomEnglishWords
      .filter((word) => word !== chosenRandomWord)
      .sort(() => Math.random() - 0.5);

    const firstWrongPhoto = await getUrlToPhoto(notChosenWords.at(0) as string);
    const secondWrongPhoto = await getUrlToPhoto(notChosenWords.at(1) as string);
    const thirdWrongPhoto = await getUrlToPhoto(notChosenWords.at(2) as string);
    return {
      word: chosenRandomWord,
      photo: url,
      wrongPhotos: [firstWrongPhoto, secondWrongPhoto, thirdWrongPhoto],
    };
  }
}
